name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # a cada 12 horas certinho (meia-noite e meio-dia)
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Gera a cobra
      - uses: Platane/snk@v3
        with:
          github_user_name: Oliveiirazl
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Publica no GitHub Pages
      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
